name: Fun Fact

permalink: /episodes/:title

url: "http://www.funfact.fm/"

# Applying a variant of this workaround for a Netlify Jekyll issue that popped up Feb 2023 
# https://talk.jekyllrb.com/t/jekyll-on-mac-could-not-read-file-and-invalid-date-error-using-bundle-exec-jekyll-serve/7664
exclude: "cache/bundle"

future: true
